CREATE TABLE IF NOT EXISTS venues (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    capacity INT UNSIGNED NOT NULL,
    seat_id_format VARCHAR(255) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    layout JSON DEFAULT NULL,
    `address` TEXT DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
